project:
  type: website
execute:
  freeze: auto
website:
  title: "Geospatial data cubes in Julia workshop"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
    - intro_ndarrays.qmd
    - section: "Julia Introduction"
      contents:
      - intro_julia.qmd
      - intro-repl.qmd
      - href: intro-pkg.qmd
        text: Package Manager
    - section: "Exercises"
      contents:
      - exercise_timeseries.qmd
      - exercise_yaxarrays.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



